Feature/dashboard
marcosppm/laundry-react pull request #3
Opened 2019-10-06 02:11 UTC by marcosppm

Barra superior e tabs finalizadas, exibindo conteudo mockado.

<div align='center'>
![preview](https://user-images.githubusercontent.com/18462645/66263222-4c86ff80-e7c5-11e9-89c0-92675fe184b4.png)
</div>

2019-10-08 13:46 UTC, felipewaku requested changes

2019-10-08 13:46 UTC, felipewaku commented on package.json
> +    "typescript": "3.6.3"
typescript e types deveriam estar nas devDependencies

2019-10-08 13:46 UTC, felipewaku commented on src/resources/constants.ts
> +  public static readonly Secondary = DefaultColor.BlueJeans;
Por que usou classe e parâmetros estáticos?

2019-10-08 13:46 UTC, felipewaku commented on src/resources/constants.ts
> +export enum FontSize {
Por que enum em vez de objeto?

2019-10-08 13:46 UTC, felipewaku commented on src/resources/constants.ts
> +export enum DefaultColor {
Por que DeafultColor? Não poderia ser só color?

2019-10-08 13:46 UTC, felipewaku commented on src/resources/images/index.ts
> +}
Precisa disso? Isso me parece bastante react-native 😬 Na web geralmente usamos outros métodos, consegue procurar?

2019-10-08 13:46 UTC, felipewaku commented on src/index.js
> +	}
A indentação dessa classe esta muito estranha... Não dava para utilizar dois espaços?

2019-10-08 13:46 UTC, felipewaku commented on src/index.css
> +  font: 14px "Century Gothic", Futura, sans-serif;
Não adianta muito definir o enum FontSize se não usar ele depois 😛

2019-10-08 13:46 UTC, felipewaku commented on src/app/dashboard/dashboard.container.tsx
> +export class DashboardContainer extends React.Component {
Por que container?

2019-10-08 13:46 UTC, felipewaku commented on src/app/dashboard/dashboard.component.tsx
> +        return <H1 key={key}>{machineTitle}</H1>
H1 só deveria ser título da página

2019-10-08 13:46 UTC, felipewaku commented on src/app/dashboard/dashboard.component.tsx
> +  <Tabs id={"residences-main-tab"}>
Por que está usando esse id?

2019-10-08 13:46 UTC, felipewaku commented on src/app/dashboard/dashboard.component.tsx
> +const DashboardHeader = () => (
Em vez desse header provavlemente precisava usar nav da web e esse componente não deveria estar no dashboard

2019-10-08 13:46 UTC, felipewaku commented on src/app/dashboard/dashboard.container.tsx
> +export class DashboardContainer extends React.Component {
Acho que container é um nome bem ruim dado que já existe Container do bootstrap e pode acabar confundindo

2019-10-20 20:38 UTC, marcosppm commented on src/resources/constants.ts
> +  public static readonly Secondary = DefaultColor.BlueJeans;
Foi o único jeito que achei pra atribuir as cores pra variáveis com nomes semânticos.

2019-10-20 20:38 UTC, marcosppm commented on src/resources/constants.ts
> +export enum DefaultColor {
fica em conflito com o `enum Color { ... }`

2019-10-20 21:02 UTC, marcosppm commented on src/app/dashboard/dashboard.component.tsx
> +  <Tabs id={"residences-main-tab"}>
é um atributo obrigatório do componente

2019-10-26 23:40 UTC, merged